CREATE TABLE `articles` (
	`id` text PRIMARY KEY NOT NULL,
	`feed_id` text NOT NULL,
	`original_id` text,
	`title` text NOT NULL,
	`title_type` text,
	`description` text,
	`description_type` text,
	`content` text,
	`link` text NOT NULL,
	`links` text,
	`comments` text,
	`author_name` text,
	`author_email` text,
	`author_uri` text,
	`contributors` text,
	`categories` text,
	`published` integer,
	`published_raw` text,
	`updated` integer,
	`updated_raw` text,
	`pub_date` integer,
	`is_read` integer DEFAULT false NOT NULL,
	`is_starred` integer DEFAULT false NOT NULL,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`feed_id`) REFERENCES `feeds`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `feeds` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`link` text NOT NULL,
	`feed_url` text NOT NULL,
	`type` text,
	`generator` text,
	`language` text,
	`copyright` text,
	`docs` text,
	`ttl` integer,
	`skip_days` text,
	`skip_hours` text,
	`managing_editor` text,
	`author_name` text,
	`author_email` text,
	`author_uri` text,
	`categories` text,
	`custom_channels` text,
	`published` integer,
	`created` integer,
	`update_date` integer,
	`last_build_date` integer,
	`created_at` integer,
	`updated_at` integer
);
--> statement-breakpoint
CREATE UNIQUE INDEX `feeds_feed_url_unique` ON `feeds` (`feed_url`);